# .github/workflows/main.yml
name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 23
      uses: actions/setup-java@v2
      with:
        java-version: '23'
        distribution: 'temurin'  # Укажите дистрибутив JDK

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test
